/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej3b2.h"
#include <stdlib.h>
#include <stdio.h>
salida *
ejecutartarea_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static salida  result;

	int i=0;
	int j=0;
	while (i<256){
	  *(result.datos+j)=*(argp->datos1+i)/10*8+9-6;
	  j++;
	  *(result.datos+j)=*(argp->datos1+i)/10*8+9-6;
	  j++;
	  i++;
	}

	return &result;
}
