/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej3b2.h"
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h> 
#include <time.h>

void
ej3b1_1(char *host)
{
	CLIENT *clnt;
	salida  *result_1;
	entrada  ejecutartarea_1_arg;
	double tiemponano;
	struct timespec ti_nano, tf_nano;
	char aux;
	int i;
#ifndef	DEBUG
	clnt = clnt_create (host, ej3b1, ej3b1v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//genero un numero aleatorio
	srand(time(NULL));
	
	for (i=0;i<256;i++){
	  *(ejecutartarea_1_arg.datos1+i)=rand();
	  *(ejecutartarea_1_arg.datos2+i)=rand();
	}
	printf ("Se generaron 2 argumentos con 256 datos de tipo LONG (4 bytes) como entrada a la llamada local\n");
	//ejecuto la llamada al servidor
	clock_gettime(CLOCK_REALTIME, &ti_nano);  // Instante inicial
	result_1 = ejecutartarea_1(&ejecutartarea_1_arg, clnt);
	clock_gettime(CLOCK_REALTIME, &tf_nano);  // Instante final
	if (result_1 == (salida *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	//calculo el tiempo de ejecucion en el servidor
	tiemponano= (tf_nano.tv_sec - ti_nano.tv_sec)*1000000000 + (tf_nano.tv_nsec - ti_nano.tv_nsec);
	//muestro los resultados
	printf ("La llamada a LocalCall demoro %g us | %g ns\n",tiemponano/1000,tiemponano);
	printf ("desea ver el resultado de la salida s/n \n");
	aux=getchar();
	if (aux=='s'){
	for (i=0;i<512;i++)
	  printf("salida[%i]:%lu\n",i,(result_1->datos[i])); 
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ej3b1_1 (host);
exit (0);
}
