/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej7.h"
#include <sys/time.h>

tiempo *
horasistema_1_svc(void *argp, struct svc_req *rqstp)
{
	static tiempo  result;
        struct timeval tiempo;
	
	gettimeofday(&tiempo,NULL);
	result.seconds=tiempo.tv_sec;
	result.useconds=tiempo.tv_usec;

	return &result;
}
