/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej7.h"
#include <sys/time.h>

void
ej7_1(char *host)
{
	CLIENT *clnt;
	tiempo  *TiempoServer;
	char *horasistema_1_arg;
	long ajuste,diferencia;
        struct timeval ti,tf;
#ifndef	DEBUG
	clnt = clnt_create (host, ej7, ej7v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
        gettimeofday(&ti,NULL);//tiempo inicial local
	TiempoServer = horasistema_1((void*)&horasistema_1_arg, clnt);
	gettimeofday(&tf,NULL); //tiempo final local
	if (TiempoServer == (tiempo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	ajuste = (TiempoServer->seconds*1000000+TiempoServer->useconds) + ((tf.tv_sec*1000000+tf.tv_usec)-(ti.tv_sec*1000000+ti.tv_usec))/2;
	diferencia = (tf.tv_sec*1000000+tf.tv_usec) - ajuste;
	printf("\nLa variación del reloj local con respecto a la maquina %s es : %ld us\n\n",host,diferencia);	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int i=1;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	while (i<argc){
	  ej7_1 (argv[i]);
	  i++;
	}
exit (0);
}
