/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ej3b2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

salida *
ejecutartarea_1(entrada *argp, CLIENT *clnt)
{
	static salida clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ejecutartarea,
		(xdrproc_t) xdr_entrada, (caddr_t) argp,
		(xdrproc_t) xdr_salida, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
