/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej3b1.h"
#include <stdlib.h>
#include <stdio.h>
u_long *
ejecutartarea_1_svc(u_long *argp, struct svc_req *rqstp)
{
	static u_long  result;

	result=*argp/8*2+9-6;
	printf ("Soy el servidor y realice la siguiente operacion aritmetica, entrada/8*2+6-9), que fue asignada a la salida\n");
	return &result;
}
