/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej5b.h"
#include "time.h"
#include <utmp.h>
#include <err.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
char **
tiempo_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	char output[9];
	// struct para obtener tiempo
	const struct tm *loctim;
	// operaciones para obtener la hora del sistema
	time_t rawtime;
	time(&rawtime);
	loctim = localtime ( &rawtime );
	// guardar en result la hora
	
        strftime(output,9,"%H:%M:%S\n",loctim);
        result=(char*)malloc(sizeof(char)*9);
        //result=output;
        strcpy(result,output);
	return &result;
}

char **
fecha_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	char output[9];
	// struct para obtener tiempo
	const struct tm *loctim;
	// operaciones para obtener la hora del sistema
	time_t rawtime;
	time ( &rawtime );
	loctim = localtime ( &rawtime );
	// guardar en result la hora
		strftime(output,9,"%d/%m/%y",loctim);
        result=(char*)malloc(sizeof(char)*9);
        //result=output;
        strcpy(result,output);

	return &result;
}

char **
nombre_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	char mensaje[256];
	gethostname(mensaje, 256);
	result=(char*)malloc(sizeof(char)*256);
	 strcpy(result,mensaje);
	return &result;
}

int *
usuarioslog_1_svc(void *argp, struct svc_req *rqstp)
{
	 static int result;
	 FILE *fp ;
	 int ch=0;
	 int lines=0;
         system ("who >> usuarios.txt");
	 fp = fopen("usuarios.txt","r");
	 if (fp == NULL)
	    return 0;
	 lines++;
	 while ((ch = fgetc(fp)) != EOF)
	 {
	    if (ch == '\n')
		      lines++;
	 }
	 fclose(fp);
	 system ("rm usuarios.txt");

	result=lines;
	return &result;
}

