/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej5b.h"
#include <string.h>
void menu();
void
ej5b_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *tiempo_1_arg;
	char * *result_2;
	char *fecha_1_arg;
	char * *result_3;
	char *nombre_1_arg;
	int  *result_4;
	char *usuarioslog_1_arg;
	int opcion;
	opcion=5;

#ifndef	DEBUG
	clnt = clnt_create (host, ej5b, ver_ej5b, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while (opcion!=0){
	  menu();
	  scanf("%i", &opcion);
	  if (opcion==1){
	    result_1 = tiempo_1((void*)&tiempo_1_arg, clnt);
	    if (result_1 == (char **) NULL) {
		    clnt_perror (clnt, "call failed");
	    }
	    printf("Hora del sistema:%s\n", *result_1);
	  }
	   if (opcion==2){
	    result_2 = fecha_1((void*)&fecha_1_arg, clnt);
	    if (result_2 == (char **) NULL) {
		    clnt_perror (clnt, "call failed");
	    }
	    printf("Fecha del sistema:%s\n", *result_2);
	  }
	  if (opcion==3){
	    result_3 = nombre_1((void*)&nombre_1_arg, clnt);
	    if (result_3 == (char **) NULL) {
		    clnt_perror (clnt, "call failed");
	    }
	    printf("Nombre del server:%s\n", *result_3);

	  }
	  if (opcion==4){
	    result_4 = usuarioslog_1((void*)&usuarioslog_1_arg, clnt);
	    if (result_4 == (int *) NULL) {
		    clnt_perror (clnt, "call failed");
	    }
	    printf("Cantidad de usuarios Logueados:%i\n", *result_4);

	  }
	  if (opcion==0){
	     printf ("FIN\n");
	  }
	  
	}
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ej5b_1 (host);
exit (0);
}

void menu (){
  printf("\n*********************** Preguntas ***********************\n");
  printf("1- Solicitar la hora del sistema\n1- Solicitar la fecha del sistema\n3- Solicitar el nombre del sistema\n4- Solicitar informacion sobre la cantidad de usuarios logueados\n0- Finalizar\n \n");
	
}