/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJ5B_H_RPCGEN
#define _EJ5B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ej5b 0x20009991
#define ver_ej5b 1

#if defined(__STDC__) || defined(__cplusplus)
#define tiempo 1
extern  char ** tiempo_1(void *, CLIENT *);
extern  char ** tiempo_1_svc(void *, struct svc_req *);
#define fecha 2
extern  char ** fecha_1(void *, CLIENT *);
extern  char ** fecha_1_svc(void *, struct svc_req *);
#define nombre 3
extern  char ** nombre_1(void *, CLIENT *);
extern  char ** nombre_1_svc(void *, struct svc_req *);
#define usuariosLog 4
extern  int * usuarioslog_1(void *, CLIENT *);
extern  int * usuarioslog_1_svc(void *, struct svc_req *);
extern int ej5b_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define tiempo 1
extern  char ** tiempo_1();
extern  char ** tiempo_1_svc();
#define fecha 2
extern  char ** fecha_1();
extern  char ** fecha_1_svc();
#define nombre 3
extern  char ** nombre_1();
extern  char ** nombre_1_svc();
#define usuariosLog 4
extern  int * usuarioslog_1();
extern  int * usuarioslog_1_svc();
extern int ej5b_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJ5B_H_RPCGEN */
