/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJ2B_H_RPCGEN
#define _EJ2B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ej2b 0x20000001
#define ej2bv1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ejecutartarea 1
extern  int * ejecutartarea_1(int *, CLIENT *);
extern  int * ejecutartarea_1_svc(int *, struct svc_req *);
extern int ej2b_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ejecutartarea 1
extern  int * ejecutartarea_1();
extern  int * ejecutartarea_1_svc();
extern int ej2b_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJ2B_H_RPCGEN */
